name: bolt12.dart
description: An implementation of BOLT12 in dart lang.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bech32: ^0.2.1
  bip340:
    git:
      url: https://github.com/vincenzopalazzo/dart-bip340.git
      ref: dart/nullsafety
  crypto: ^3.0.1
  hex: ^0.2.0
  tuple: ^2.0.0
dev_dependencies: 
  test: ^1.17.12
