---
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  node-test:
    name: Node Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Nodejs ${{ matrix.node-version }} install
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pyln-proto >= 0.10.1' 'python-dateutil >= 2.8.2' 'bech32 >= 1.2.0'
          npm install secp256k1
          npm install js-sha256
          npm install bip-schnorr
          npm install xmlhttprequest
      - name: Build and check
        run: |
          make -C javascript check

  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Python ${{ matrix.python-version }} install
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install 'pyln-proto >= 0.10.1' 'python-dateutil >= 2.8.2' 'bech32 >= 1.2.0'
      - name: Build and check
        run: |
          make -C python check

  bolt-tests:
    name: BOLT Quote Tests
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pyln-proto >= 0.10.1' 'python-dateutil >= 2.8.2' 'bech32 >= 1.2.0'
      - name: Build and check
        run: |
          make check-quotes
